<?php

namespace Epfc\JobeetBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    public function countActiveJobs($category_id = null)
    {
      $qb = $this->createQueryBuilder('j')
        ->select('count(j.id)')
        ->where('j.expires_at > :date')
        ->setParameter('date', date('Y-m-d H:i:s', time()));

      if($category_id)
      {
        $qb->andWhere('j.category = :category_id')
        ->setParameter('category_id', $category_id);
      }

      $query = $qb->getQuery();

      return $query->getSingleScalarResult();
    }
}
